import { StyleSheet } from 'react-native';

import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    image: {
        width: width,
        height: height,
    },
    title: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#fff',
        position: 'absolute',
        top: '10%',
        transform: [{ translateY: -16 }],
        left: 20,
        marginRight: 40,
        textShadowColor: 'blue',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 5,
        zIndex: 1,
    },
    button: {
        backgroundColor: 'rgba(14, 14, 14, 0.9)',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 16,
        position: 'absolute',
        bottom: '10%',
        margin: 'auto',
        textAlignVertical: 'center',
        display: 'flex',
        alignItems: 'center',
        lineHeight: '10px',
    },
    buttonText: {
        display: 'flex',
        alignItems: 'center',
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
    },
    bookPage: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: width,
        height: height,
    },
    bookPagePhoto: {
        position: 'absolute',
        borderTopWidth: 200,
        borderStyle: 'solid',
        borderColor: 'rgba(0, 0, 0, 0.0)',
        width: 250,
        height: 250,
    },
    content: {
        alignItems: 'center',
        justifyContent: 'center',
        position: 'absolute',
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
    },
    gifEagle: {
        width: 150,
        height: 150,
        resizeMode: 'contain',
        position: 'absolute',
        ustifyContent: 'center',
        top: '460px',
        left: '50%',
    },
    boar: {
        width: 400,
        height: 400,
    },
    arrow: {
        position: 'absolute',
        top: '50%',
        padding: 16,
    },
    endBook: {
        position: 'absolute',
    },
    endBookImage: {
        width: 64,
        height: 64,
        resizeMode: 'contain',
        position: 'absolute',
        transform: [{ translateY: 491 }],
        right: '81px',
    },
    endBookImageClosed: {
        width: 64,
        height: 64,
        resizeMode: 'contain',
        position: 'absolute',
        transform: [{ translateY: 475 }],
        right: '-130px',
    },
    arrowImageLeft: {
        width: 64,
        height: 64,
        resizeMode: 'contain',
        position: 'absolute',
        transform: [{ translateY: 575 }],
        left: '-400%',
    },
    arrowImageRight: {
        width: 64,
        height: 64,
        resizeMode: 'contain',
        position: 'absolute',
        transform: [{ translateY: 575 }],
        left: '300%',
    },
    text: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        marginHorizontal: 32,
        marginTop: 32,
    },
    pageText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
        position: 'absolute',
        top: '20%',
        transform: [{ translateY: 50 }],
        left: 20,
        marginRight: 40,
        textShadowColor: 'black',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 5,
    },
    pageCard: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        transform: [{ translateY: 225 }],
        right: -222,
        width: 355,
        height: 195,
    },
    pageCardExit: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        transform: [{ translateY: 535 }],
        left: 80,
        width: 355,
        height: 195,
    },
    pageTextBoar: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
        position: 'absolute',
        top: '20%',
        transform: [{ translateY: 150 }],
        left: -175,
        marginRight: 40,
        textShadowColor: 'black',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 5,
    },
    pageTextCat: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'white',
        position: 'absolute',
        top: '20%',
        transform: [{ translateY: 50 }],
        left: -175,
        textShadowColor: 'black',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 5,
    },
    pageTextBottom: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        top: '350px',
        transform: [{ translateY: 100 }],
        left: 20,
        marginRight: 40,
        textShadowColor: 'white',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 5,

    },
    pageTextBottomBoar: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        top: '350px',
        transform: [{ translateY: 70 }],
        left: 20,
        marginRight: 40,
        textShadowColor: 'white',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 5,

    },
    pageTextBottomCat: {
        fontSize: 24,
        fontWeight: 'bold',
        color: 'black',
        position: 'absolute',
        top: '350px',
        transform: [{ translateY: 70 }],
        left: 20,
        marginRight: 40,
        textShadowColor: 'white',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 5,

    },
    opacityBoar: {
        width: 355,
        height: 195,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    opacityEagle: {
        width: 355,
        height: 195,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    opacityCat: {
        width: 355,
        height: 230,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    subtitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginTop: 16,
    },
    link: {
        fontSize: 20,
        color: 'blue',
    },
    likedTale: {
        marginTop: 20,
        fontSize: 20,
        color: 'black',
        display: 'block',
        textShadowColor: 'orange',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 1,
        width: 255
    },
    questionnaireButton: {
        display: 'inline-block',
        backgroundColor: 'orange',
        color: 'black',
        borderRadius: 16,
        fontSize: 20,
        borderStyle: 'solid',
        borderWidth: 1,
        lineHeight: 40,
    },
    buttonCenter: {
        marginTop: 20,
        marginLeft: 65,
    },

    //questionnaire
    containerQ: {
        flexGrow: 1,
        padding: 16,
    },
    titleQ: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 16,
        marginLeft: 90,
    },
    question: {
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 16,
    },
    input: {
        borderWidth: 1,
        borderColor: 'gray',
        borderRadius: 4,
        padding: 8,
        marginTop: 8,
        marginBottom: 16,
    },
    radioButton: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 8,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'gray',
        padding: 8,
    },
    radioButtonSingle: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 8,
        marginLeft: -35,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'gray',
        padding: 8,
    },
    radioButtonSelected: {
        backgroundColor: 'gray',
    },
    radioButtonText: {
        marginLeft: 8,
        fontSize: 16,
    },
    selectedValues: {
        marginTop: 24,
    },
    selectedValueText: {
        fontSize: 16,
    },
    submitButton: {
        backgroundColor: 'blue',
        borderRadius: 4,
        padding: 12,
        alignItems: 'center',
        marginTop: 16,
    },
    downloadButton: {
        backgroundColor: 'green',
        borderRadius: 4,
        padding: 8,
        alignItems: 'center',
        marginTop: 8,
    },
    submitButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    downloadButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    chipContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 8,
        marginBottom: 16,
    },
    chip: {
        marginRight: 8,
        marginBottom: 8,
    },
    chipSelected: {
        backgroundColor: 'gray',
    },
    radioButtonGroup: {
        marginLeft: 35
    },
    checkBoxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 8,
    },
    checkBox: {
        marginRight: 8,
    },
    checkBoxLabel: {
        fontSize: 16,
    },
});

export default styles;